### ISSUE TITLE
Implement AUC ROC and average precision measures to assess AD results.

### ISSUE THREAD

**Issue by dhonza** [LogAnalysisTeam/ml4logs#2]
We need to get a better idea of how different AD methods compare. The benchmark suite currently measures precision, recall, and F1, only.

Add AUC ROC and average precision measures so we know, how the models behave regardless of the threshold selection.

**Problem**: How to deal with unsupervised AD algorithms?

**Comment by OpeningNew** [comment]
## Preliminary results

Dataset: HDFS1

| Model              | AUC   | AP    | Precision | Recall | F1    |
| ------------------ | ----- | ----- | --------- | ------ | ----- |
| Tree               | 0.995 | 0.990 | 1.0       | 0.990  | 0.995 |
| LogisticRegression | 0.995 | 0.848 | 0.836     | 0.999  | 0.911 |
| LinearSVC          | 0.996 | 0.962 | 0.960     | 0.978  | 0.969 |
| IsolationForest    | 0.843 | 0.361 | 0.053     | 0.689  | 0.099 |
| OneClassSVM        | 0.994 | 0.732 | 0.075     | 1.0    | 0.140 |
