### ISSUE TITLE
Add Drain3 to the benchmark suite and compare it with other parsers

### ISSUE THREAD

**Issue by dhonza** [LogAnalysisTeam/ml4logs#4]
Include Drain3 (https://github.com/IBM/Drain3) to the LAD benchmarking suite. Compare with other approaches (Spell, Drain, ...).

**Comment by savchart** [comment]
comparative table: [https://docs.google.com/spreadsheets/d/1WmZkejQiu0RuaH59PyKRtbzsj4kNP8ET7ekW6biTb48/edit?usp=sharing](url)
The results are approximately the same: origin_drain - 44 ids, drain3 - 45 ids.
Drain3  works better with parameters.
If I'm not mistaken Drain3 does not support saving results to file.
